### ISSUE TITLE
Threads and bindings

### ISSUE THREAD

**Issue by snipervld** [Julien-Mialon/StormXamarin#5]
Hello <s>finding bugs continues</s>. Today I'm with threading issue. Assume we have viewmodel with string property and, view with textview that binds to this VM and timer that do some calculations. When timer update that string property (and RaisePropertyChanged() raises), program throws an exception (TargetInvocationException) that means accessing UI from non-UI thread (you know that)).
Hope I described that issue correctly.

**Comment by snipervld** [comment]
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Android.Util.AndroidRuntimeException: Exception of type 'Android.Util.AndroidRuntimeException' was thrown.
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61 
at Android.Runtime.JNIEnv.CallVoidMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue\* parms) [0x00069] in <filename unknown>:0 
at Android.Widget.TextView.set_TextFormatted (ICharSequence value) [0x00051] in <filename unknown>:0 
at Android.Widget.TextView.set_Text (System.String value) [0x00013] in <filename unknown>:0 
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00044] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:230 
--- End of managed exception stack trace ---
at Android.Widget.TextView.set_Text (System.String val09-22 19:19:55.975 E/mono    (20165): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6363)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:909)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:4691)
at android.view.View.invalidateInternal(View.java:11802)
at android.view.View.invalidate(View.java:11766)
at android.view.View.invalidate(View.java:11750)
at android.widget.TextView.checkForRelayout(TextView.java:6861)
at android.widget.TextView.setText(TextView.java:4060)
at android.widget.TextView.setText(TextView.java:3918)
at android.widget.TextView.setText(TextView.java:3893)

--- End of inner exception stack trace ---
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0005c] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:238 
at System.Reflection.MonoProperty.SetValue (System.Object obj, System.Object value, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] index, System.Globalization.CultureInfo culture) [0x0006a] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Reflection/MonoProperty.cs:366 
at System.Reflection.PropertyInfo.SetValue (System.Object obj, System.Object value) [0x00000] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Reflection/PropertyInfo.cs:118 
at **Storm.Mvvm.Bindings.DependencyPropertyProxy.SetValue** (System.Object value) [0x0005b] in <filename unknown>:0 
at **Storm.Mvvm.Bindings.PropertyBinding.UpdateValue** (System.Object value) [0x0005a] in <filename unknown>:0 
at Storm.Mvvm.Bindings.BindingNode.UpdateValue (System.Object value) [0x000bd] in <filename unknown>:0 
at Storm.Mvvm.Bindings.BindingNode.OnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00032] in <filename unknown>:0 
at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
at Storm.Mvvm.NotifierBase.RaisePropertyChanged (System.String propertyName) [0x00012] in <filename unknown>:0 
......

**Comment by Julien-Mialon** [comment]
This threading issue came from your code and not from the framework in this case.
The workaround to run actions on ui thread when you're not in this thread is to use IDispatcherService. But it's a common issue with ui update. 
The other possibility would be to change the framework in order that every binding operation are run on ui thread but it could slow the app in general case.

**Comment by snipervld** [comment]
Thank you for you answer. I create IDispatcher (as you say) which has method <code>Invoke</code>. Then in vm with timer i override <code>RaisePropertyChanged</code> (wrapper) in which call <code>IDispatcher.Invoke(...)</code> and ... profit! No errors! Thank you again.
