### ISSUE TITLE
After update

### ISSUE THREAD

**Issue by snipervld** [Julien-Mialon/StormXamarin#6]
After update there is a new issue. "Resources.Layout doesn't contain 'Main_DT_SpinnerItemTemplate'", but SpinnerItemTemplate is defined in resources sections of Main.xml. This occurs with both Debug and Release configurations.
https://onedrive.live.com/redir?resid=BE878B196C95461B!1072&authkey=!ADwyuXFYEVBNNXU&ithint=file%2crar

**Comment by Julien-Mialon** [comment]
Hello,

Just look into your project, you have a Resource.Designer.cs file in your Assets folder, remove it and add the one in Resources to your project, it should work better.

**Comment by snipervld** [comment]
<s>Stupid error. I missed it</s>

And real issue: missed Adapter.

FATAL EXCEPTION: main
Process: AndroidTest.AndroidTest, PID: 19069
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.ArgumentException: Set Method not found for 'Adapter'
at System.Reflection.MonoProperty.SetValue (object,object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x00168>
at System.Reflection.PropertyInfo.SetValue (object,object) <0x0004f>
at AndroidTest.MainActivity.Generated_AssignResourceForView () <0x00063>
at AndroidTest.MainActivity.GetBindingPaths () <0x0001b>
at Storm.Mvvm.ActivityBase.SetViewModel (Storm.Mvvm.ViewModelBase) <0x00033>
at AndroidTest.MainActivity.OnCreate (Android.OS.Bundle) <0x0007b>
at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) <0x0005b>
at (wrapper dynamic-method) object.5da34ebf-1f27-4f53-8121-91cf6b726317 (intptr,intptr,intptr) <0x00043>

at md57cbbacfe57e84d5f2316e7fd1c806491.MainActivity.n_onCreate(Native Method)
at md57cbbacfe57e84d5f2316e7fd1c806491.MainActivity.onCreate(MainActivity.java:28)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
at android.app.ActivityThread.access$900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5293)
... 4 more

**Comment by snipervld** [comment]
Oops. I make mistake: use Cast  instead of Select
https://onedrive.live.com/redir?resid=BE878B196C95461B!1072&authkey=!ADwyuXFYEVBNNXU&ithint=file%2crar

But it doesn't improve situation.
Also this appears only in Release mode

**Comment by Julien-Mialon** [comment]
I'm gonna look into it, I already find one issue coming from the fact that ListView expect an IListAdapter and not just an IAdapter. This things will be fixed easily but your error doesn't seems to come from here.

**Comment by Julien-Mialon** [comment]
After looking deeper, adapter used in binding implement IListAdapter as it should.
In fact the problem come from the release configuration, in this configuration, if you check in your project properties : Android Options / Linker, Linking Sdk Assemblies remove every method which is not explicitly used and therefore remove the Set method on the adapter property of the ListView because it's not used by your code, the mvvm framework or the Android framework.

I gonna ask this question on Xamarin forums if there is any possibility to get rid of this without disabling the linker.
http://forums.xamarin.com/discussion/51690/xamarin-android-linker-reflection

**Comment by snipervld** [comment]
I have a suggestion: MvvmCross have file LinkerPleaseInclude.cs. Maybe here use MvvmCross's temporary solution?

``` c#
class Linker
{
        public void Include(View v)
        {
            v.Click += delegate { };
            v.ContextMenuCreated += delegate { };
            v.Drag += delegate { };
            v.FocusChange += delegate { };
            v.GenericMotion += delegate { };
            v.LayoutChange += delegate { };
            v.LongClick += delegate { };
            v.SystemUiVisibilityChange += delegate { };
            v.Touch += delegate { };
            v.ViewAttachedToWindow += delegate { };
            v.ViewDetachedFromWindow += delegate { };
        }

        public void Include(EditText v) { v.TextChanged += delegate { }; }

        public void Include(TextView v) { v.Text = v.Text + ""; }

        public void Include(AbsListView v) { v.Adapter = null; }

        public void Include(AbsSpinner v) { v.Adapter = null; }

        public void Include(BindableSpinner v)
        {
            v.CurrentItem = null;
            v.CurrentItemChanged += delegate { };
        }

        public void Include(BindableListView v)
        {
            v.CurrentItem = null;
            v.CurrentItemChanged += delegate { };
        }
}
```

or use Linker.xml: https://developer.xamarin.com/guides/cross-platform/advanced/custom_linking/

**Comment by Julien-Mialon** [comment]
The file from MvvmCross seems to be a good solution, thanks. The Linker.xml will have a simple issue, it's supposed to be used in the final project and the goal here is not really to add one more file.

I will try with the LinkerPleaseInclude file from MvvmCross.
